name: Node CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            # - name: install system deps
            #   run: sudo apt-get install libxi-dev libgl1-mesa-dev
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install, build, and test
              run: |
                  npm install
                  npm run build --if-present
                  npm run test:verbose
              env:
                  CI: true
